MERAK_SERVICE = "dipper-merak"
PHECDA_SERVICE = "dipper-phecda"

RESULT_OK = 200
RESULT_FAIL = 400
RESULT_NULL = 500
RESULT_SUCCESS_STR = "SUCCESS"
RESULT_FAIL_STR = "FAIL"
RESULT_FAIL_NULL = "NULL"

FRIEND = "FRIEND"
FRIEND_MESSAGE = "FRIEND_MESSAGE"
FRIEND_TYPE = "FRIEND_TYPE"
GROUP = "GROUP"
GROUP_USE = "GROUP_USER"
USER = "USER"

USER_ADDRESS = "localhost:7078"

BLOG_ADDRESS = "localhost:9700"

IMAGE_BASE = "http://localhost:9701/dipper/fs/"
