# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import BaseService_pb2 as BaseService__pb2


class BaseServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.save = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/save',
        request_serializer=BaseService__pb2.Entry.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.deleteById = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/deleteById',
        request_serializer=BaseService__pb2.KeyId.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.deleteByPropertyList = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/deleteByPropertyList',
        request_serializer=BaseService__pb2.Entry.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.update = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/update',
        request_serializer=BaseService__pb2.Entry.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.selectById = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/selectById',
        request_serializer=BaseService__pb2.KeyId.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.selectAll = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/selectAll',
        request_serializer=BaseService__pb2.Empty.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.selectByProperty = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/selectByProperty',
        request_serializer=BaseService__pb2.Entry.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.selectListByProperty = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/selectListByProperty',
        request_serializer=BaseService__pb2.Entry.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )
    self.selectPageList = channel.unary_unary(
        '/com.dipper.proto.rpc.BaseService/selectPageList',
        request_serializer=BaseService__pb2.PageInfo.SerializeToString,
        response_deserializer=BaseService__pb2.RpcResult.FromString,
        )


class BaseServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def save(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def deleteByPropertyList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def selectById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def selectAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def selectByProperty(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def selectListByProperty(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def selectPageList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BaseServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'save': grpc.unary_unary_rpc_method_handler(
          servicer.save,
          request_deserializer=BaseService__pb2.Entry.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'deleteById': grpc.unary_unary_rpc_method_handler(
          servicer.deleteById,
          request_deserializer=BaseService__pb2.KeyId.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'deleteByPropertyList': grpc.unary_unary_rpc_method_handler(
          servicer.deleteByPropertyList,
          request_deserializer=BaseService__pb2.Entry.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=BaseService__pb2.Entry.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'selectById': grpc.unary_unary_rpc_method_handler(
          servicer.selectById,
          request_deserializer=BaseService__pb2.KeyId.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'selectAll': grpc.unary_unary_rpc_method_handler(
          servicer.selectAll,
          request_deserializer=BaseService__pb2.Empty.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'selectByProperty': grpc.unary_unary_rpc_method_handler(
          servicer.selectByProperty,
          request_deserializer=BaseService__pb2.Entry.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'selectListByProperty': grpc.unary_unary_rpc_method_handler(
          servicer.selectListByProperty,
          request_deserializer=BaseService__pb2.Entry.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
      'selectPageList': grpc.unary_unary_rpc_method_handler(
          servicer.selectPageList,
          request_deserializer=BaseService__pb2.PageInfo.FromString,
          response_serializer=BaseService__pb2.RpcResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.dipper.proto.rpc.BaseService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
