# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlogService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BlogService.proto',
  package='com.dipper.proto.rpc',
  syntax='proto3',
  serialized_options=b'\n\024com.dipper.proto.rpcB\tBlogProtoP\001',
  serialized_pb=b'\n\x11\x42logService.proto\x12\x14\x63om.dipper.proto.rpc\"j\n\x07\x42logPro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0e\n\x06header\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x12\n\nbuild_time\x18\x06 \x01(\tB#\n\x14\x63om.dipper.proto.rpcB\tBlogProtoP\x01\x62\x06proto3'
)




_BLOGPRO = _descriptor.Descriptor(
  name='BlogPro',
  full_name='com.dipper.proto.rpc.BlogPro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.dipper.proto.rpc.BlogPro.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.dipper.proto.rpc.BlogPro.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='com.dipper.proto.rpc.BlogPro.header', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.dipper.proto.rpc.BlogPro.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='com.dipper.proto.rpc.BlogPro.image', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_time', full_name='com.dipper.proto.rpc.BlogPro.build_time', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['BlogPro'] = _BLOGPRO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlogPro = _reflection.GeneratedProtocolMessageType('BlogPro', (_message.Message,), {
  'DESCRIPTOR' : _BLOGPRO,
  '__module__' : 'BlogService_pb2'
  # @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.BlogPro)
  })
_sym_db.RegisterMessage(BlogPro)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
