# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FriendService.proto',
  package='com.dipper.proto.rpc',
  syntax='proto3',
  serialized_options=b'\n\024com.dipper.proto.rpcB\013FriendProtoP\001',
  serialized_pb=b'\n\x13\x46riendService.proto\x12\x14\x63om.dipper.proto.rpc\"r\n\tFriendPro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x11\n\tfriend_id\x18\x04 \x01(\x05\x12\x12\n\nbuild_time\x18\x05 \x01(\t\x12\x0f\n\x07type_id\x18\x06 \x01(\x05\x32\x0f\n\rFriendServiceB%\n\x14\x63om.dipper.proto.rpcB\x0b\x46riendProtoP\x01\x62\x06proto3'
)




_FRIENDPRO = _descriptor.Descriptor(
  name='FriendPro',
  full_name='com.dipper.proto.rpc.FriendPro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.dipper.proto.rpc.FriendPro.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.dipper.proto.rpc.FriendPro.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='com.dipper.proto.rpc.FriendPro.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friend_id', full_name='com.dipper.proto.rpc.FriendPro.friend_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_time', full_name='com.dipper.proto.rpc.FriendPro.build_time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='com.dipper.proto.rpc.FriendPro.type_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['FriendPro'] = _FRIENDPRO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FriendPro = _reflection.GeneratedProtocolMessageType('FriendPro', (_message.Message,), {
  'DESCRIPTOR' : _FRIENDPRO,
  '__module__' : 'FriendService_pb2'
  # @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.FriendPro)
  })
_sym_db.RegisterMessage(FriendPro)


DESCRIPTOR._options = None

_FRIENDSERVICE = _descriptor.ServiceDescriptor(
  name='FriendService',
  full_name='com.dipper.proto.rpc.FriendService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=161,
  serialized_end=176,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_FRIENDSERVICE)

DESCRIPTOR.services_by_name['FriendService'] = _FRIENDSERVICE

# @@protoc_insertion_point(module_scope)
