# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendTypeService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FriendTypeService.proto',
  package='com.dipper.proto.rpc',
  syntax='proto3',
  serialized_options=b'\n\024com.dipper.proto.rpcB\017FriendTypeProtoP\001',
  serialized_pb=b'\n\x17\x46riendTypeService.proto\x12\x14\x63om.dipper.proto.rpc\"g\n\rFriendTypePro\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttype_name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x12\n\nbuild_time\x18\x04 \x01(\t\x12\x12\n\nis_default\x18\x05 \x01(\x05\x32\x13\n\x11\x46riendTypeServiceB)\n\x14\x63om.dipper.proto.rpcB\x0f\x46riendTypeProtoP\x01\x62\x06proto3'
)




_FRIENDTYPEPRO = _descriptor.Descriptor(
  name='FriendTypePro',
  full_name='com.dipper.proto.rpc.FriendTypePro',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.dipper.proto.rpc.FriendTypePro.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_name', full_name='com.dipper.proto.rpc.FriendTypePro.type_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.dipper.proto.rpc.FriendTypePro.user_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_time', full_name='com.dipper.proto.rpc.FriendTypePro.build_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_default', full_name='com.dipper.proto.rpc.FriendTypePro.is_default', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['FriendTypePro'] = _FRIENDTYPEPRO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FriendTypePro = _reflection.GeneratedProtocolMessageType('FriendTypePro', (_message.Message,), {
  'DESCRIPTOR' : _FRIENDTYPEPRO,
  '__module__' : 'FriendTypeService_pb2'
  # @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.FriendTypePro)
  })
_sym_db.RegisterMessage(FriendTypePro)


DESCRIPTOR._options = None

_FRIENDTYPESERVICE = _descriptor.ServiceDescriptor(
  name='FriendTypeService',
  full_name='com.dipper.proto.rpc.FriendTypeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=173,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_FRIENDTYPESERVICE)

DESCRIPTOR.services_by_name['FriendTypeService'] = _FRIENDTYPESERVICE

# @@protoc_insertion_point(module_scope)
