# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImageService.proto',
  package='com.dipper.proto.rpc',
  syntax='proto3',
  serialized_options=b'\n\024com.dipper.proto.rpcB\nImageProtoP\001',
  serialized_pb=b'\n\x12ImageService.proto\x12\x14\x63om.dipper.proto.rpc\"(\n\tImageData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05photo\x18\x02 \x01(\x0c\"A\n\x0fImageSaveResult\x12\x10\n\x08rpc_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"\x18\n\tImagePath\x12\x0b\n\x03url\x18\x01 \x01(\t\"C\n\x0fImageLoadResult\x12\x10\n\x08rpc_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05photo\x18\x03 \x01(\x0c\x32\xb6\x01\n\x0cImageService\x12P\n\x04save\x12\x1f.com.dipper.proto.rpc.ImageData\x1a%.com.dipper.proto.rpc.ImageSaveResult\"\x00\x12T\n\x08\x64ownload\x12\x1f.com.dipper.proto.rpc.ImagePath\x1a%.com.dipper.proto.rpc.ImageLoadResult\"\x00\x42$\n\x14\x63om.dipper.proto.rpcB\nImageProtoP\x01\x62\x06proto3'
)




_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='com.dipper.proto.rpc.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.dipper.proto.rpc.ImageData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='photo', full_name='com.dipper.proto.rpc.ImageData.photo', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=84,
)


_IMAGESAVERESULT = _descriptor.Descriptor(
  name='ImageSaveResult',
  full_name='com.dipper.proto.rpc.ImageSaveResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc_code', full_name='com.dipper.proto.rpc.ImageSaveResult.rpc_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.dipper.proto.rpc.ImageSaveResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='com.dipper.proto.rpc.ImageSaveResult.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=151,
)


_IMAGEPATH = _descriptor.Descriptor(
  name='ImagePath',
  full_name='com.dipper.proto.rpc.ImagePath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='com.dipper.proto.rpc.ImagePath.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=177,
)


_IMAGELOADRESULT = _descriptor.Descriptor(
  name='ImageLoadResult',
  full_name='com.dipper.proto.rpc.ImageLoadResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpc_code', full_name='com.dipper.proto.rpc.ImageLoadResult.rpc_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.dipper.proto.rpc.ImageLoadResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='photo', full_name='com.dipper.proto.rpc.ImageLoadResult.photo', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['ImageSaveResult'] = _IMAGESAVERESULT
DESCRIPTOR.message_types_by_name['ImagePath'] = _IMAGEPATH
DESCRIPTOR.message_types_by_name['ImageLoadResult'] = _IMAGELOADRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'ImageService_pb2'
  # @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.ImageData)
  })
_sym_db.RegisterMessage(ImageData)

ImageSaveResult = _reflection.GeneratedProtocolMessageType('ImageSaveResult', (_message.Message,), {
  'DESCRIPTOR' : _IMAGESAVERESULT,
  '__module__' : 'ImageService_pb2'
  # @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.ImageSaveResult)
  })
_sym_db.RegisterMessage(ImageSaveResult)

ImagePath = _reflection.GeneratedProtocolMessageType('ImagePath', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEPATH,
  '__module__' : 'ImageService_pb2'
  # @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.ImagePath)
  })
_sym_db.RegisterMessage(ImagePath)

ImageLoadResult = _reflection.GeneratedProtocolMessageType('ImageLoadResult', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELOADRESULT,
  '__module__' : 'ImageService_pb2'
  # @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.ImageLoadResult)
  })
_sym_db.RegisterMessage(ImageLoadResult)


DESCRIPTOR._options = None

_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='ImageService',
  full_name='com.dipper.proto.rpc.ImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=249,
  serialized_end=431,
  methods=[
  _descriptor.MethodDescriptor(
    name='save',
    full_name='com.dipper.proto.rpc.ImageService.save',
    index=0,
    containing_service=None,
    input_type=_IMAGEDATA,
    output_type=_IMAGESAVERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download',
    full_name='com.dipper.proto.rpc.ImageService.download',
    index=1,
    containing_service=None,
    input_type=_IMAGEPATH,
    output_type=_IMAGELOADRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['ImageService'] = _IMAGESERVICE

# @@protoc_insertion_point(module_scope)
