// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BlogMessageService.proto

package com_dipper_proto_rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlogMessagePro struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogId               int32    `protobuf:"varint,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MsgType              int32    `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	BuildTime            int32    `protobuf:"varint,6,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlogMessagePro) Reset()         { *m = BlogMessagePro{} }
func (m *BlogMessagePro) String() string { return proto.CompactTextString(m) }
func (*BlogMessagePro) ProtoMessage()    {}
func (*BlogMessagePro) Descriptor() ([]byte, []int) {
	return fileDescriptor_28757189f03a4f57, []int{0}
}

func (m *BlogMessagePro) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlogMessagePro.Unmarshal(m, b)
}
func (m *BlogMessagePro) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlogMessagePro.Marshal(b, m, deterministic)
}
func (m *BlogMessagePro) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlogMessagePro.Merge(m, src)
}
func (m *BlogMessagePro) XXX_Size() int {
	return xxx_messageInfo_BlogMessagePro.Size(m)
}
func (m *BlogMessagePro) XXX_DiscardUnknown() {
	xxx_messageInfo_BlogMessagePro.DiscardUnknown(m)
}

var xxx_messageInfo_BlogMessagePro proto.InternalMessageInfo

func (m *BlogMessagePro) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlogMessagePro) GetBlogId() int32 {
	if m != nil {
		return m.BlogId
	}
	return 0
}

func (m *BlogMessagePro) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BlogMessagePro) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *BlogMessagePro) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BlogMessagePro) GetBuildTime() int32 {
	if m != nil {
		return m.BuildTime
	}
	return 0
}

func init() {
	proto.RegisterType((*BlogMessagePro)(nil), "com.dipper.proto.rpc.BlogMessagePro")
}

func init() {
	proto.RegisterFile("BlogMessageService.proto", fileDescriptor_28757189f03a4f57)
}

var fileDescriptor_28757189f03a4f57 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x14, 0x45, 0x49, 0x75, 0x5a, 0xe7, 0x2d, 0x06, 0x09, 0x03, 0xc6, 0x85, 0x30, 0xb8, 0x1a, 0x5c,
	0x74, 0xa1, 0x7f, 0xd0, 0xdd, 0x2c, 0x84, 0x61, 0xec, 0xbe, 0xd8, 0xe4, 0x11, 0x1e, 0x34, 0x7d,
	0x21, 0x49, 0x85, 0xfe, 0x90, 0xdf, 0x29, 0x4d, 0x11, 0x14, 0x5d, 0xde, 0x73, 0xb8, 0x8b, 0x03,
	0xaa, 0x19, 0xd8, 0xbe, 0x62, 0x8c, 0xef, 0x16, 0xdf, 0x30, 0x7c, 0x90, 0xc6, 0xda, 0x07, 0x4e,
	0x2c, 0xf7, 0x9a, 0x5d, 0x6d, 0xc8, 0x7b, 0x0c, 0x2b, 0xa9, 0x83, 0xd7, 0x8f, 0x9f, 0x02, 0x76,
	0x3f, 0x2e, 0xe7, 0xc0, 0x72, 0x07, 0x05, 0x19, 0x25, 0x0e, 0xe2, 0xb8, 0xb9, 0x14, 0x64, 0xe4,
	0x1d, 0x54, 0xfd, 0xc0, 0xb6, 0x23, 0xa3, 0x8a, 0x0c, 0xcb, 0x65, 0x9e, 0xb2, 0x98, 0x22, 0x86,
	0x45, 0x5c, 0xad, 0x62, 0x99, 0x27, 0x23, 0xef, 0xe1, 0xc6, 0x45, 0xdb, 0xa5, 0xd9, 0xa3, 0xba,
	0xce, 0xa6, 0x72, 0xd1, 0xb6, 0xb3, 0x47, 0xa9, 0xa0, 0xd2, 0x3c, 0x26, 0x1c, 0x93, 0xda, 0x1c,
	0xc4, 0x71, 0x7b, 0xf9, 0x9e, 0xf2, 0x01, 0xa0, 0x9f, 0x68, 0x30, 0x5d, 0x22, 0x87, 0xaa, 0xcc,
	0xb7, 0x6d, 0x26, 0x2d, 0x39, 0x7c, 0xde, 0x83, 0xfc, 0x9b, 0xd6, 0x3c, 0xc1, 0xbf, 0x59, 0xcd,
	0xed, 0xef, 0xa6, 0xc4, 0x67, 0xd1, 0x97, 0x59, 0xbf, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x91,
	0x93, 0x81, 0xb5, 0x23, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BlogMessageServiceClient is the client API for BlogMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlogMessageServiceClient interface {
}

type blogMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogMessageServiceClient(cc grpc.ClientConnInterface) BlogMessageServiceClient {
	return &blogMessageServiceClient{cc}
}

// BlogMessageServiceServer is the server API for BlogMessageService service.
type BlogMessageServiceServer interface {
}

// UnimplementedBlogMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlogMessageServiceServer struct {
}

func RegisterBlogMessageServiceServer(s *grpc.Server, srv BlogMessageServiceServer) {
	s.RegisterService(&_BlogMessageService_serviceDesc, srv)
}

var _BlogMessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.dipper.proto.rpc.BlogMessageService",
	HandlerType: (*BlogMessageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "BlogMessageService.proto",
}
