// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FriendTypeService.proto

package com_dipper_proto_rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FriendTypePro struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeName             string   `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BuildTime            string   `protobuf:"bytes,4,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	IsDefault            int32    `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendTypePro) Reset()         { *m = FriendTypePro{} }
func (m *FriendTypePro) String() string { return proto.CompactTextString(m) }
func (*FriendTypePro) ProtoMessage()    {}
func (*FriendTypePro) Descriptor() ([]byte, []int) {
	return fileDescriptor_449be894d104f4f8, []int{0}
}

func (m *FriendTypePro) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendTypePro.Unmarshal(m, b)
}
func (m *FriendTypePro) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendTypePro.Marshal(b, m, deterministic)
}
func (m *FriendTypePro) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendTypePro.Merge(m, src)
}
func (m *FriendTypePro) XXX_Size() int {
	return xxx_messageInfo_FriendTypePro.Size(m)
}
func (m *FriendTypePro) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendTypePro.DiscardUnknown(m)
}

var xxx_messageInfo_FriendTypePro proto.InternalMessageInfo

func (m *FriendTypePro) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FriendTypePro) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *FriendTypePro) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FriendTypePro) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func (m *FriendTypePro) GetIsDefault() int32 {
	if m != nil {
		return m.IsDefault
	}
	return 0
}

func init() {
	proto.RegisterType((*FriendTypePro)(nil), "com.dipper.proto.rpc.FriendTypePro")
}

func init() {
	proto.RegisterFile("FriendTypeService.proto", fileDescriptor_449be894d104f4f8)
}

var fileDescriptor_449be894d104f4f8 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0x75, 0x57, 0x33, 0xa0, 0x62, 0x14, 0x36, 0x20, 0xc2, 0xe2, 0x69, 0xbd, 0xf4,
	0xa0, 0x6f, 0x50, 0x44, 0xf0, 0x22, 0xa5, 0xf6, 0x1e, 0xda, 0xce, 0x08, 0x03, 0x4d, 0x13, 0xd2,
	0x54, 0xe8, 0x73, 0xf8, 0xc2, 0xd2, 0xf4, 0x20, 0xe2, 0x1e, 0xe7, 0xfb, 0xf9, 0x60, 0x3e, 0xd8,
	0xbd, 0x06, 0xa6, 0x01, 0xeb, 0xd9, 0xd3, 0x07, 0x85, 0x2f, 0xee, 0x28, 0xf7, 0xc1, 0x45, 0xa7,
	0x6e, 0x3b, 0x67, 0x73, 0x64, 0xef, 0x29, 0xac, 0x24, 0x0f, 0xbe, 0x7b, 0xf8, 0x16, 0x70, 0xf1,
	0x6b, 0x94, 0xc1, 0xa9, 0x4b, 0xc8, 0x18, 0xb5, 0xd8, 0x8b, 0xc3, 0xa6, 0xca, 0x18, 0xd5, 0x1d,
	0xc8, 0x38, 0x7b, 0x32, 0x43, 0x63, 0x49, 0x67, 0x7b, 0x71, 0x90, 0xd5, 0xf9, 0x02, 0xde, 0x1b,
	0x4b, 0x6a, 0x07, 0x67, 0xd3, 0x48, 0xc1, 0x30, 0xea, 0x93, 0x64, 0x6c, 0x97, 0xf3, 0x0d, 0xd5,
	0x3d, 0x40, 0x3b, 0x71, 0x8f, 0x26, 0xb2, 0x25, 0x7d, 0x9a, 0x34, 0x99, 0x48, 0xcd, 0x96, 0x96,
	0x99, 0x47, 0x83, 0xf4, 0xd9, 0x4c, 0x7d, 0xd4, 0x9b, 0xa4, 0x4a, 0x1e, 0x5f, 0x56, 0xf0, 0x74,
	0x03, 0xd7, 0xff, 0x32, 0x8a, 0x47, 0x38, 0x9a, 0x50, 0x5c, 0xfd, 0xf9, 0x3f, 0xba, 0x52, 0xb4,
	0xdb, 0xb4, 0x3e, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x10, 0x28, 0xbf, 0x0d, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FriendTypeServiceClient is the client API for FriendTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FriendTypeServiceClient interface {
}

type friendTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendTypeServiceClient(cc grpc.ClientConnInterface) FriendTypeServiceClient {
	return &friendTypeServiceClient{cc}
}

// FriendTypeServiceServer is the server API for FriendTypeService service.
type FriendTypeServiceServer interface {
}

// UnimplementedFriendTypeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFriendTypeServiceServer struct {
}

func RegisterFriendTypeServiceServer(s *grpc.Server, srv FriendTypeServiceServer) {
	s.RegisterService(&_FriendTypeService_serviceDesc, srv)
}

var _FriendTypeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.dipper.proto.rpc.FriendTypeService",
	HandlerType: (*FriendTypeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "FriendTypeService.proto",
}
