// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GroupUserService.proto

package com_dipper_proto_rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupUserPro struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId              int32    `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	JoinTime             string   `protobuf:"bytes,4,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupUserPro) Reset()         { *m = GroupUserPro{} }
func (m *GroupUserPro) String() string { return proto.CompactTextString(m) }
func (*GroupUserPro) ProtoMessage()    {}
func (*GroupUserPro) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfd922aa5ecbd3ba, []int{0}
}

func (m *GroupUserPro) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupUserPro.Unmarshal(m, b)
}
func (m *GroupUserPro) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupUserPro.Marshal(b, m, deterministic)
}
func (m *GroupUserPro) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupUserPro.Merge(m, src)
}
func (m *GroupUserPro) XXX_Size() int {
	return xxx_messageInfo_GroupUserPro.Size(m)
}
func (m *GroupUserPro) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupUserPro.DiscardUnknown(m)
}

var xxx_messageInfo_GroupUserPro proto.InternalMessageInfo

func (m *GroupUserPro) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GroupUserPro) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupUserPro) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupUserPro) GetJoinTime() string {
	if m != nil {
		return m.JoinTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GroupUserPro)(nil), "com.dipper.proto.rpc.GroupUserPro")
}

func init() {
	proto.RegisterFile("GroupUserService.proto", fileDescriptor_dfd922aa5ecbd3ba)
}

var fileDescriptor_dfd922aa5ecbd3ba = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x4f, 0x0b, 0x82, 0x40,
	0x10, 0x47, 0x59, 0x2b, 0xff, 0x0c, 0x21, 0xb1, 0x44, 0x19, 0x5d, 0xa4, 0x93, 0x27, 0x0f, 0xf5,
	0x0d, 0xbc, 0x84, 0x37, 0xb1, 0x3a, 0x0b, 0xb9, 0x4b, 0x4c, 0x60, 0xb3, 0x8c, 0xda, 0xe7, 0x8f,
	0xdd, 0x20, 0x22, 0x3a, 0xfe, 0xde, 0x9b, 0x81, 0x07, 0xab, 0x23, 0xd3, 0x68, 0x2e, 0xbd, 0xe6,
	0x93, 0xe6, 0x27, 0xb6, 0x3a, 0x37, 0x4c, 0x03, 0xc9, 0x65, 0x4b, 0x5d, 0xae, 0xd0, 0x18, 0xcd,
	0x6f, 0x92, 0xb3, 0x69, 0x77, 0x04, 0xf3, 0xcf, 0x7d, 0xc5, 0x24, 0x63, 0xf0, 0x50, 0x25, 0x22,
	0x15, 0xd9, 0xac, 0xf6, 0x50, 0xc9, 0x35, 0x04, 0x63, 0xaf, 0xb9, 0x41, 0x95, 0x78, 0x0e, 0xfa,
	0x76, 0x96, 0x4a, 0x6e, 0x20, 0xbc, 0xd9, 0x47, 0x6b, 0x26, 0xce, 0x04, 0x6e, 0x97, 0x4a, 0x6e,
	0x21, 0xba, 0x13, 0x3e, 0x9a, 0x01, 0x3b, 0x9d, 0x4c, 0x53, 0x91, 0x45, 0x75, 0x68, 0xc1, 0x19,
	0x3b, 0xbd, 0x97, 0xb0, 0xf8, 0x0d, 0x2c, 0x32, 0xf8, 0x1b, 0x57, 0xc4, 0xdf, 0x69, 0x03, 0x55,
	0xe2, 0xea, 0x3b, 0x79, 0x78, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x4c, 0x45, 0xd0, 0xe5, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GroupUserServiceClient is the client API for GroupUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupUserServiceClient interface {
}

type groupUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupUserServiceClient(cc grpc.ClientConnInterface) GroupUserServiceClient {
	return &groupUserServiceClient{cc}
}

// GroupUserServiceServer is the server API for GroupUserService service.
type GroupUserServiceServer interface {
}

// UnimplementedGroupUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGroupUserServiceServer struct {
}

func RegisterGroupUserServiceServer(s *grpc.Server, srv GroupUserServiceServer) {
	s.RegisterService(&_GroupUserService_serviceDesc, srv)
}

var _GroupUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.dipper.proto.rpc.GroupUserService",
	HandlerType: (*GroupUserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "GroupUserService.proto",
}
