// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlogMessageService.proto

package com.dipper.proto.rpc;

public final class BlogMessageProto {
  private BlogMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_BlogMessagePro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_BlogMessagePro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030BlogMessageService.proto\022\024com.dipper.p" +
      "roto.rpc\"u\n\016BlogMessagePro\022\n\n\002id\030\001 \001(\005\022\017" +
      "\n\007blog_id\030\002 \001(\005\022\017\n\007user_id\030\003 \001(\005\022\020\n\010msg_" +
      "type\030\004 \001(\005\022\017\n\007content\030\005 \001(\t\022\022\n\nbuild_tim" +
      "e\030\006 \001(\0052\024\n\022BlogMessageServiceB*\n\024com.dip" +
      "per.proto.rpcB\020BlogMessageProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dipper_proto_rpc_BlogMessagePro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dipper_proto_rpc_BlogMessagePro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_BlogMessagePro_descriptor,
        new java.lang.String[] { "Id", "BlogId", "UserId", "MsgType", "Content", "BuildTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
