// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseService.proto

package com.dipper.proto.rpc;

public interface DataListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dipper.proto.rpc.DataList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.Any data = 1;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getDataList();
  /**
   * <code>repeated .google.protobuf.Any data = 1;</code>
   */
  com.google.protobuf.Any getData(int index);
  /**
   * <code>repeated .google.protobuf.Any data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .google.protobuf.Any data = 1;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any data = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder(
      int index);
}
