// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseService.proto

package com.dipper.proto.rpc;

public final class DipperService {
  private DipperService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_RpcResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_RpcResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_DataList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_DataList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_KeyId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_KeyId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_EntryList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_EntryList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_PageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_PageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BaseService.proto\022\024com.dipper.proto.rp" +
      "c\032\031google/protobuf/any.proto\032\021UserServic" +
      "e.proto\"R\n\tRpcResult\022\020\n\010rpc_code\030\001 \001(\005\022\017" +
      "\n\007message\030\002 \001(\t\022\"\n\004data\030\003 \001(\0132\024.google.p" +
      "rotobuf.Any\"8\n\005Empty\022/\n\004type\030\001 \001(\0162!.com" +
      ".dipper.proto.rpc.MessageType\".\n\010DataLis" +
      "t\022\"\n\004data\030\001 \003(\0132\024.google.protobuf.Any\"H\n" +
      "\005KeyId\022/\n\004type\030\001 \001(\0162!.com.dipper.proto." +
      "rpc.MessageType\022\016\n\006key_id\030\002 \001(\005\"]\n\005Entry" +
      "\022/\n\004type\030\001 \001(\0162!.com.dipper.proto.rpc.Me" +
      "ssageType\022#\n\005entry\030\002 \001(\0132\024.google.protob" +
      "uf.Any\"a\n\tEntryList\022/\n\004type\030\001 \001(\0162!.com." +
      "dipper.proto.rpc.MessageType\022#\n\005entry\030\002 " +
      "\003(\0132\024.google.protobuf.Any\"`\n\010PageInfo\022/\n" +
      "\004type\030\001 \001(\0162!.com.dipper.proto.rpc.Messa" +
      "geType\022\020\n\010page_num\030\002 \001(\005\022\021\n\tpage_size\030\003 " +
      "\001(\005*v\n\013MessageType\022\n\n\006FRIEND\020\000\022\022\n\016FRIEND" +
      "_MESSAGE\020\001\022\017\n\013FRIEND_TYPE\020\002\022\t\n\005GROUP\020\003\022\016" +
      "\n\nGROUP_USER\020\004\022\010\n\004USER\020\005\022\021\n\rGROUP_MESSAG" +
      "E\020\0062\341\005\n\013BaseService\022F\n\004save\022\033.com.dipper" +
      ".proto.rpc.Entry\032\037.com.dipper.proto.rpc." +
      "RpcResult\"\000\022L\n\ndeleteById\022\033.com.dipper.p" +
      "roto.rpc.KeyId\032\037.com.dipper.proto.rpc.Rp" +
      "cResult\"\000\022V\n\024deleteByPropertyList\022\033.com." +
      "dipper.proto.rpc.Entry\032\037.com.dipper.prot" +
      "o.rpc.RpcResult\"\000\022H\n\006update\022\033.com.dipper" +
      ".proto.rpc.Entry\032\037.com.dipper.proto.rpc." +
      "RpcResult\"\000\022L\n\nselectById\022\033.com.dipper.p" +
      "roto.rpc.KeyId\032\037.com.dipper.proto.rpc.Rp" +
      "cResult\"\000\022K\n\tselectAll\022\033.com.dipper.prot" +
      "o.rpc.Empty\032\037.com.dipper.proto.rpc.RpcRe" +
      "sult\"\000\022R\n\020selectByProperty\022\033.com.dipper." +
      "proto.rpc.Entry\032\037.com.dipper.proto.rpc.R" +
      "pcResult\"\000\022V\n\024selectListByProperty\022\033.com" +
      ".dipper.proto.rpc.Entry\032\037.com.dipper.pro" +
      "to.rpc.RpcResult\"\000\022S\n\016selectPageList\022\036.c" +
      "om.dipper.proto.rpc.PageInfo\032\037.com.dippe" +
      "r.proto.rpc.RpcResult\"\000B\'\n\024com.dipper.pr" +
      "oto.rpcB\rDipperServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.dipper.proto.rpc.UserProto.getDescriptor(),
        });
    internal_static_com_dipper_proto_rpc_RpcResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dipper_proto_rpc_RpcResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_RpcResult_descriptor,
        new java.lang.String[] { "RpcCode", "Message", "Data", });
    internal_static_com_dipper_proto_rpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dipper_proto_rpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_Empty_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_com_dipper_proto_rpc_DataList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_dipper_proto_rpc_DataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_DataList_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_com_dipper_proto_rpc_KeyId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_dipper_proto_rpc_KeyId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_KeyId_descriptor,
        new java.lang.String[] { "Type", "KeyId", });
    internal_static_com_dipper_proto_rpc_Entry_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_dipper_proto_rpc_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_Entry_descriptor,
        new java.lang.String[] { "Type", "Entry", });
    internal_static_com_dipper_proto_rpc_EntryList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_dipper_proto_rpc_EntryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_EntryList_descriptor,
        new java.lang.String[] { "Type", "Entry", });
    internal_static_com_dipper_proto_rpc_PageInfo_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_dipper_proto_rpc_PageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_PageInfo_descriptor,
        new java.lang.String[] { "Type", "PageNum", "PageSize", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.dipper.proto.rpc.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
