// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseService.proto

package com.dipper.proto.rpc;

public interface EntryListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dipper.proto.rpc.EntryList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.dipper.proto.rpc.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.dipper.proto.rpc.MessageType type = 1;</code>
   * @return The type.
   */
  com.dipper.proto.rpc.MessageType getType();

  /**
   * <code>repeated .google.protobuf.Any entry = 2;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getEntryList();
  /**
   * <code>repeated .google.protobuf.Any entry = 2;</code>
   */
  com.google.protobuf.Any getEntry(int index);
  /**
   * <code>repeated .google.protobuf.Any entry = 2;</code>
   */
  int getEntryCount();
  /**
   * <code>repeated .google.protobuf.Any entry = 2;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getEntryOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any entry = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getEntryOrBuilder(
      int index);
}
