// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendService.proto

package com.dipper.proto.rpc;

public interface FriendProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dipper.proto.rpc.FriendPro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 user_id = 2;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int32 friend_id = 4;</code>
   * @return The friendId.
   */
  int getFriendId();

  /**
   * <code>string build_time = 5;</code>
   * @return The buildTime.
   */
  java.lang.String getBuildTime();
  /**
   * <code>string build_time = 5;</code>
   * @return The bytes for buildTime.
   */
  com.google.protobuf.ByteString
      getBuildTimeBytes();

  /**
   * <code>int32 type_id = 6;</code>
   * @return The typeId.
   */
  int getTypeId();
}
