// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendTypeService.proto

package com.dipper.proto.rpc;

public interface FriendTypeProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dipper.proto.rpc.FriendTypePro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string type_name = 2;</code>
   * @return The typeName.
   */
  java.lang.String getTypeName();
  /**
   * <code>string type_name = 2;</code>
   * @return The bytes for typeName.
   */
  com.google.protobuf.ByteString
      getTypeNameBytes();

  /**
   * <code>int32 user_id = 3;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string build_time = 4;</code>
   * @return The buildTime.
   */
  java.lang.String getBuildTime();
  /**
   * <code>string build_time = 4;</code>
   * @return The bytes for buildTime.
   */
  com.google.protobuf.ByteString
      getBuildTimeBytes();

  /**
   * <code>int32 is_default = 5;</code>
   * @return The isDefault.
   */
  int getIsDefault();
}
