// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupService.proto

package com.dipper.proto.rpc;

/**
 * Protobuf type {@code com.dipper.proto.rpc.GroupPro}
 */
public  final class GroupPro extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.dipper.proto.rpc.GroupPro)
    GroupProOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GroupPro.newBuilder() to construct.
  private GroupPro(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupPro() {
    groupName_ = "";
    avatar_ = "";
    sendTime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GroupPro();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GroupPro(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            groupNum_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            groupName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            avatar_ = s;
            break;
          }
          case 40: {

            isDel_ = input.readInt32();
            break;
          }
          case 48: {

            isRead_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            sendTime_ = s;
            break;
          }
          case 64: {

            isBack_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dipper.proto.rpc.GroupProto.internal_static_com_dipper_proto_rpc_GroupPro_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dipper.proto.rpc.GroupProto.internal_static_com_dipper_proto_rpc_GroupPro_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dipper.proto.rpc.GroupPro.class, com.dipper.proto.rpc.GroupPro.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  public static final int GROUP_NUM_FIELD_NUMBER = 2;
  private int groupNum_;
  /**
   * <code>int32 group_num = 2;</code>
   * @return The groupNum.
   */
  public int getGroupNum() {
    return groupNum_;
  }

  public static final int GROUP_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object groupName_;
  /**
   * <code>string group_name = 3;</code>
   * @return The groupName.
   */
  public java.lang.String getGroupName() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupName_ = s;
      return s;
    }
  }
  /**
   * <code>string group_name = 3;</code>
   * @return The bytes for groupName.
   */
  public com.google.protobuf.ByteString
      getGroupNameBytes() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATAR_FIELD_NUMBER = 4;
  private volatile java.lang.Object avatar_;
  /**
   * <code>string avatar = 4;</code>
   * @return The avatar.
   */
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <code>string avatar = 4;</code>
   * @return The bytes for avatar.
   */
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_DEL_FIELD_NUMBER = 5;
  private int isDel_;
  /**
   * <code>int32 is_del = 5;</code>
   * @return The isDel.
   */
  public int getIsDel() {
    return isDel_;
  }

  public static final int IS_READ_FIELD_NUMBER = 6;
  private int isRead_;
  /**
   * <code>int32 is_read = 6;</code>
   * @return The isRead.
   */
  public int getIsRead() {
    return isRead_;
  }

  public static final int SEND_TIME_FIELD_NUMBER = 7;
  private volatile java.lang.Object sendTime_;
  /**
   * <code>string send_time = 7;</code>
   * @return The sendTime.
   */
  public java.lang.String getSendTime() {
    java.lang.Object ref = sendTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sendTime_ = s;
      return s;
    }
  }
  /**
   * <code>string send_time = 7;</code>
   * @return The bytes for sendTime.
   */
  public com.google.protobuf.ByteString
      getSendTimeBytes() {
    java.lang.Object ref = sendTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sendTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_BACK_FIELD_NUMBER = 8;
  private int isBack_;
  /**
   * <code>int32 is_back = 8;</code>
   * @return The isBack.
   */
  public int getIsBack() {
    return isBack_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (groupNum_ != 0) {
      output.writeInt32(2, groupNum_);
    }
    if (!getGroupNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, groupName_);
    }
    if (!getAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, avatar_);
    }
    if (isDel_ != 0) {
      output.writeInt32(5, isDel_);
    }
    if (isRead_ != 0) {
      output.writeInt32(6, isRead_);
    }
    if (!getSendTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, sendTime_);
    }
    if (isBack_ != 0) {
      output.writeInt32(8, isBack_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (groupNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, groupNum_);
    }
    if (!getGroupNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, groupName_);
    }
    if (!getAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, avatar_);
    }
    if (isDel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, isDel_);
    }
    if (isRead_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, isRead_);
    }
    if (!getSendTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, sendTime_);
    }
    if (isBack_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, isBack_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dipper.proto.rpc.GroupPro)) {
      return super.equals(obj);
    }
    com.dipper.proto.rpc.GroupPro other = (com.dipper.proto.rpc.GroupPro) obj;

    if (getId()
        != other.getId()) return false;
    if (getGroupNum()
        != other.getGroupNum()) return false;
    if (!getGroupName()
        .equals(other.getGroupName())) return false;
    if (!getAvatar()
        .equals(other.getAvatar())) return false;
    if (getIsDel()
        != other.getIsDel()) return false;
    if (getIsRead()
        != other.getIsRead()) return false;
    if (!getSendTime()
        .equals(other.getSendTime())) return false;
    if (getIsBack()
        != other.getIsBack()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + GROUP_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getGroupNum();
    hash = (37 * hash) + GROUP_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getGroupName().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + IS_DEL_FIELD_NUMBER;
    hash = (53 * hash) + getIsDel();
    hash = (37 * hash) + IS_READ_FIELD_NUMBER;
    hash = (53 * hash) + getIsRead();
    hash = (37 * hash) + SEND_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getSendTime().hashCode();
    hash = (37 * hash) + IS_BACK_FIELD_NUMBER;
    hash = (53 * hash) + getIsBack();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dipper.proto.rpc.GroupPro parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dipper.proto.rpc.GroupPro parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dipper.proto.rpc.GroupPro parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dipper.proto.rpc.GroupPro parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dipper.proto.rpc.GroupPro prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.dipper.proto.rpc.GroupPro}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.dipper.proto.rpc.GroupPro)
      com.dipper.proto.rpc.GroupProOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dipper.proto.rpc.GroupProto.internal_static_com_dipper_proto_rpc_GroupPro_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dipper.proto.rpc.GroupProto.internal_static_com_dipper_proto_rpc_GroupPro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dipper.proto.rpc.GroupPro.class, com.dipper.proto.rpc.GroupPro.Builder.class);
    }

    // Construct using com.dipper.proto.rpc.GroupPro.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      groupNum_ = 0;

      groupName_ = "";

      avatar_ = "";

      isDel_ = 0;

      isRead_ = 0;

      sendTime_ = "";

      isBack_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dipper.proto.rpc.GroupProto.internal_static_com_dipper_proto_rpc_GroupPro_descriptor;
    }

    @java.lang.Override
    public com.dipper.proto.rpc.GroupPro getDefaultInstanceForType() {
      return com.dipper.proto.rpc.GroupPro.getDefaultInstance();
    }

    @java.lang.Override
    public com.dipper.proto.rpc.GroupPro build() {
      com.dipper.proto.rpc.GroupPro result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.dipper.proto.rpc.GroupPro buildPartial() {
      com.dipper.proto.rpc.GroupPro result = new com.dipper.proto.rpc.GroupPro(this);
      result.id_ = id_;
      result.groupNum_ = groupNum_;
      result.groupName_ = groupName_;
      result.avatar_ = avatar_;
      result.isDel_ = isDel_;
      result.isRead_ = isRead_;
      result.sendTime_ = sendTime_;
      result.isBack_ = isBack_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dipper.proto.rpc.GroupPro) {
        return mergeFrom((com.dipper.proto.rpc.GroupPro)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dipper.proto.rpc.GroupPro other) {
      if (other == com.dipper.proto.rpc.GroupPro.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getGroupNum() != 0) {
        setGroupNum(other.getGroupNum());
      }
      if (!other.getGroupName().isEmpty()) {
        groupName_ = other.groupName_;
        onChanged();
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (other.getIsDel() != 0) {
        setIsDel(other.getIsDel());
      }
      if (other.getIsRead() != 0) {
        setIsRead(other.getIsRead());
      }
      if (!other.getSendTime().isEmpty()) {
        sendTime_ = other.sendTime_;
        onChanged();
      }
      if (other.getIsBack() != 0) {
        setIsBack(other.getIsBack());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dipper.proto.rpc.GroupPro parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dipper.proto.rpc.GroupPro) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int groupNum_ ;
    /**
     * <code>int32 group_num = 2;</code>
     * @return The groupNum.
     */
    public int getGroupNum() {
      return groupNum_;
    }
    /**
     * <code>int32 group_num = 2;</code>
     * @param value The groupNum to set.
     * @return This builder for chaining.
     */
    public Builder setGroupNum(int value) {
      
      groupNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 group_num = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupNum() {
      
      groupNum_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object groupName_ = "";
    /**
     * <code>string group_name = 3;</code>
     * @return The groupName.
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group_name = 3;</code>
     * @return The bytes for groupName.
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group_name = 3;</code>
     * @param value The groupName to set.
     * @return This builder for chaining.
     */
    public Builder setGroupName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groupName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string group_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupName() {
      
      groupName_ = getDefaultInstance().getGroupName();
      onChanged();
      return this;
    }
    /**
     * <code>string group_name = 3;</code>
     * @param value The bytes for groupName to set.
     * @return This builder for chaining.
     */
    public Builder setGroupNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groupName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <code>string avatar = 4;</code>
     * @return The avatar.
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string avatar = 4;</code>
     * @return The bytes for avatar.
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string avatar = 4;</code>
     * @param value The avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string avatar = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <code>string avatar = 4;</code>
     * @param value The bytes for avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatar_ = value;
      onChanged();
      return this;
    }

    private int isDel_ ;
    /**
     * <code>int32 is_del = 5;</code>
     * @return The isDel.
     */
    public int getIsDel() {
      return isDel_;
    }
    /**
     * <code>int32 is_del = 5;</code>
     * @param value The isDel to set.
     * @return This builder for chaining.
     */
    public Builder setIsDel(int value) {
      
      isDel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 is_del = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDel() {
      
      isDel_ = 0;
      onChanged();
      return this;
    }

    private int isRead_ ;
    /**
     * <code>int32 is_read = 6;</code>
     * @return The isRead.
     */
    public int getIsRead() {
      return isRead_;
    }
    /**
     * <code>int32 is_read = 6;</code>
     * @param value The isRead to set.
     * @return This builder for chaining.
     */
    public Builder setIsRead(int value) {
      
      isRead_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 is_read = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRead() {
      
      isRead_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sendTime_ = "";
    /**
     * <code>string send_time = 7;</code>
     * @return The sendTime.
     */
    public java.lang.String getSendTime() {
      java.lang.Object ref = sendTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sendTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string send_time = 7;</code>
     * @return The bytes for sendTime.
     */
    public com.google.protobuf.ByteString
        getSendTimeBytes() {
      java.lang.Object ref = sendTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string send_time = 7;</code>
     * @param value The sendTime to set.
     * @return This builder for chaining.
     */
    public Builder setSendTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sendTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string send_time = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSendTime() {
      
      sendTime_ = getDefaultInstance().getSendTime();
      onChanged();
      return this;
    }
    /**
     * <code>string send_time = 7;</code>
     * @param value The bytes for sendTime to set.
     * @return This builder for chaining.
     */
    public Builder setSendTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sendTime_ = value;
      onChanged();
      return this;
    }

    private int isBack_ ;
    /**
     * <code>int32 is_back = 8;</code>
     * @return The isBack.
     */
    public int getIsBack() {
      return isBack_;
    }
    /**
     * <code>int32 is_back = 8;</code>
     * @param value The isBack to set.
     * @return This builder for chaining.
     */
    public Builder setIsBack(int value) {
      
      isBack_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 is_back = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsBack() {
      
      isBack_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.dipper.proto.rpc.GroupPro)
  }

  // @@protoc_insertion_point(class_scope:com.dipper.proto.rpc.GroupPro)
  private static final com.dipper.proto.rpc.GroupPro DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dipper.proto.rpc.GroupPro();
  }

  public static com.dipper.proto.rpc.GroupPro getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupPro>
      PARSER = new com.google.protobuf.AbstractParser<GroupPro>() {
    @java.lang.Override
    public GroupPro parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GroupPro(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupPro> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GroupPro> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.dipper.proto.rpc.GroupPro getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

