// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupMessageService.proto

package com.dipper.proto.rpc;

public interface GroupMessageProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dipper.proto.rpc.GroupMessagePro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 user_id = 2;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>int32 group_id = 3;</code>
   * @return The groupId.
   */
  int getGroupId();

  /**
   * <code>string content = 4;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 4;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int32 is_del = 5;</code>
   * @return The isDel.
   */
  int getIsDel();

  /**
   * <code>int32 is_read = 6;</code>
   * @return The isRead.
   */
  int getIsRead();

  /**
   * <code>string send_time = 7;</code>
   * @return The sendTime.
   */
  java.lang.String getSendTime();
  /**
   * <code>string send_time = 7;</code>
   * @return The bytes for sendTime.
   */
  com.google.protobuf.ByteString
      getSendTimeBytes();

  /**
   * <code>int32 is_back = 8;</code>
   * @return The isBack.
   */
  int getIsBack();
}
