// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupService.proto

package com.dipper.proto.rpc;

public interface GroupProOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dipper.proto.rpc.GroupPro)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 group_num = 2;</code>
   * @return The groupNum.
   */
  int getGroupNum();

  /**
   * <code>string group_name = 3;</code>
   * @return The groupName.
   */
  java.lang.String getGroupName();
  /**
   * <code>string group_name = 3;</code>
   * @return The bytes for groupName.
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();

  /**
   * <code>string avatar = 4;</code>
   * @return The avatar.
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 4;</code>
   * @return The bytes for avatar.
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>int32 is_del = 5;</code>
   * @return The isDel.
   */
  int getIsDel();

  /**
   * <code>int32 is_read = 6;</code>
   * @return The isRead.
   */
  int getIsRead();

  /**
   * <code>string send_time = 7;</code>
   * @return The sendTime.
   */
  java.lang.String getSendTime();
  /**
   * <code>string send_time = 7;</code>
   * @return The bytes for sendTime.
   */
  com.google.protobuf.ByteString
      getSendTimeBytes();

  /**
   * <code>int32 is_back = 8;</code>
   * @return The isBack.
   */
  int getIsBack();
}
