// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupUserService.proto

package com.dipper.proto.rpc;

public final class GroupUserProto {
  private GroupUserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_GroupUserPro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_GroupUserPro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026GroupUserService.proto\022\024com.dipper.pro" +
      "to.rpc\"P\n\014GroupUserPro\022\n\n\002id\030\001 \001(\005\022\017\n\007us" +
      "er_id\030\002 \001(\005\022\020\n\010group_id\030\003 \001(\005\022\021\n\tjoin_ti" +
      "me\030\004 \001(\t2\022\n\020GroupUserServiceB(\n\024com.dipp" +
      "er.proto.rpcB\016GroupUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dipper_proto_rpc_GroupUserPro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dipper_proto_rpc_GroupUserPro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_GroupUserPro_descriptor,
        new java.lang.String[] { "Id", "UserId", "GroupId", "JoinTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
