// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupService.proto

package com.dipper.proto.rpc;

public final class GroupProto {
  private GroupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_GroupPro_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_GroupPro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022GroupService.proto\022\024com.dipper.proto.r" +
      "pc\"\222\001\n\010GroupPro\022\n\n\002id\030\001 \001(\005\022\021\n\tgroup_num" +
      "\030\002 \001(\005\022\022\n\ngroup_name\030\003 \001(\t\022\016\n\006avatar\030\004 \001" +
      "(\t\022\016\n\006is_del\030\005 \001(\005\022\017\n\007is_read\030\006 \001(\005\022\021\n\ts" +
      "end_time\030\007 \001(\t\022\017\n\007is_back\030\010 \001(\0052\016\n\014Group" +
      "ServiceB$\n\024com.dipper.proto.rpcB\nGroupPr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dipper_proto_rpc_GroupPro_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dipper_proto_rpc_GroupPro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_GroupPro_descriptor,
        new java.lang.String[] { "Id", "GroupNum", "GroupName", "Avatar", "IsDel", "IsRead", "SendTime", "IsBack", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
