// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageService.proto

package com.dipper.proto.rpc;

public final class ImageProto {
  private ImageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_ImageData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_ImageData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_ImageSaveResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_ImageSaveResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_ImagePath_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_ImagePath_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dipper_proto_rpc_ImageLoadResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dipper_proto_rpc_ImageLoadResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ImageService.proto\022\024com.dipper.proto.r" +
      "pc\"(\n\tImageData\022\014\n\004name\030\001 \001(\t\022\r\n\005photo\030\002" +
      " \001(\014\"A\n\017ImageSaveResult\022\020\n\010rpc_code\030\001 \001(" +
      "\005\022\017\n\007message\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\"\030\n\tImage" +
      "Path\022\013\n\003url\030\001 \001(\t\"C\n\017ImageLoadResult\022\020\n\010" +
      "rpc_code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\r\n\005photo" +
      "\030\003 \001(\0142\266\001\n\014ImageService\022P\n\004save\022\037.com.di" +
      "pper.proto.rpc.ImageData\032%.com.dipper.pr" +
      "oto.rpc.ImageSaveResult\"\000\022T\n\010download\022\037." +
      "com.dipper.proto.rpc.ImagePath\032%.com.dip" +
      "per.proto.rpc.ImageLoadResult\"\000B$\n\024com.d" +
      "ipper.proto.rpcB\nImageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dipper_proto_rpc_ImageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dipper_proto_rpc_ImageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_ImageData_descriptor,
        new java.lang.String[] { "Name", "Photo", });
    internal_static_com_dipper_proto_rpc_ImageSaveResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dipper_proto_rpc_ImageSaveResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_ImageSaveResult_descriptor,
        new java.lang.String[] { "RpcCode", "Message", "Url", });
    internal_static_com_dipper_proto_rpc_ImagePath_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_dipper_proto_rpc_ImagePath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_ImagePath_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_com_dipper_proto_rpc_ImageLoadResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_dipper_proto_rpc_ImageLoadResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dipper_proto_rpc_ImageLoadResult_descriptor,
        new java.lang.String[] { "RpcCode", "Message", "Photo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
