// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseService.proto

package com.dipper.proto.rpc;

public interface KeyIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dipper.proto.rpc.KeyId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.dipper.proto.rpc.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.dipper.proto.rpc.MessageType type = 1;</code>
   * @return The type.
   */
  com.dipper.proto.rpc.MessageType getType();

  /**
   * <code>int32 key_id = 2;</code>
   * @return The keyId.
   */
  int getKeyId();
}
