// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseService.proto

package com.dipper.proto.rpc;

/**
 * Protobuf enum {@code com.dipper.proto.rpc.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FRIEND = 0;</code>
   */
  FRIEND(0),
  /**
   * <code>FRIEND_MESSAGE = 1;</code>
   */
  FRIEND_MESSAGE(1),
  /**
   * <code>FRIEND_TYPE = 2;</code>
   */
  FRIEND_TYPE(2),
  /**
   * <code>GROUP = 3;</code>
   */
  GROUP(3),
  /**
   * <code>GROUP_USER = 4;</code>
   */
  GROUP_USER(4),
  /**
   * <code>USER = 5;</code>
   */
  USER(5),
  /**
   * <code>GROUP_MESSAGE = 6;</code>
   */
  GROUP_MESSAGE(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FRIEND = 0;</code>
   */
  public static final int FRIEND_VALUE = 0;
  /**
   * <code>FRIEND_MESSAGE = 1;</code>
   */
  public static final int FRIEND_MESSAGE_VALUE = 1;
  /**
   * <code>FRIEND_TYPE = 2;</code>
   */
  public static final int FRIEND_TYPE_VALUE = 2;
  /**
   * <code>GROUP = 3;</code>
   */
  public static final int GROUP_VALUE = 3;
  /**
   * <code>GROUP_USER = 4;</code>
   */
  public static final int GROUP_USER_VALUE = 4;
  /**
   * <code>USER = 5;</code>
   */
  public static final int USER_VALUE = 5;
  /**
   * <code>GROUP_MESSAGE = 6;</code>
   */
  public static final int GROUP_MESSAGE_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return FRIEND;
      case 1: return FRIEND_MESSAGE;
      case 2: return FRIEND_TYPE;
      case 3: return GROUP;
      case 4: return GROUP_USER;
      case 5: return USER;
      case 6: return GROUP_MESSAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dipper.proto.rpc.DipperService.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.dipper.proto.rpc.MessageType)
}

